<?php

/**
 * @file
 * Primary module hooks for Neo | Taxonomy module.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;
use Drupal\media\MediaInterface;
use Drupal\menu_ui\Form\MenuLinkEditForm;
use Drupal\menu_ui\MenuForm;
use Drupal\neo_image\NeoImageStyle;
use Drupal\taxonomy\TermForm;
use Drupal\taxonomy\TermInterface;
use Drupal\taxonomy_manager\Form\TaxonomyManagerForm;
use Drupal\taxonomy_manager\Form\TaxonomyManagerTermForm;

/**
 * Implements hook_form_alter().
 */
function neo_taxonomy_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'taxonomy_vocabulary_form') {
    neo_taxonomy_form_alter_form_taxonomy_vocabulary($form, $form_state);
  }
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof TermForm) {
    $term = $form_object->getEntity();
    /** @var \Drupal\taxonomy\VocabularyInterface $vocabulary */
    $vocabulary = \Drupal::entityTypeManager()->getStorage('taxonomy_vocabulary')->load($term->bundle());
    $controls = $vocabulary->getThirdPartySettings('neo_taxonomy');

    $form['status']['#weight'] = 800;
    $form['advanced']['#weight'] = 900;
    $form['actions']['#weight'] = 1000;

    if (isset($form['description']) && !empty($controls['description_format'])) {
      $form['description']['widget'][0]['#format'] = $controls['description_format'];
      $form['description']['widget'][0]['#allowed_formats'] = [$controls['description_format']];
      $form['description']['widget'][0]['#after_build'][] = 'neo_taxonomy_description_after_build';
    }

    if (isset($controls['nest']) && empty($controls['nest'])) {
      $form['relations']['#access'] = FALSE;
    }
  }

  if ($form_object instanceof MenuForm) {
    if (!empty($form['links']['links'])) {
      foreach ($form['links']['links'] as $key => &$link) {
        // If the link is a taxonomy term created by the taxonomy_menu module.
        if (str_contains($key, 'menu_plugin_id:taxonomy_menu.menu_link:taxonomy_menu.menu_link.')) {
          [$tmid, $tid] = explode('.', str_replace('menu_plugin_id:taxonomy_menu.menu_link:taxonomy_menu.menu_link.', '', $key));
          /** @var \Drupal\taxonomy\TermInterface $term */
          $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid);
          $link['title'][] = [
            '#type' => 'markup',
            '#markup' => '<small class="pl-2">' . t('Managed via Taxonomy') . '</small>',
          ];
          $link['operations']['#links']['term'] = [
            'title' => t('Manage Terms'),
            'url' => Url::fromRoute('entity.taxonomy_vocabulary.overview_form', ['taxonomy_vocabulary' => $term->bundle()]),
          ];
          unset($link['operations']['#links']['add-child']);
          unset($link['operations']['#links']['reset']);
          unset($link['operations']['#links']['delete']);
          $link['enabled']['#disabled'] = TRUE;
          $link['weight']['#disabled'] = TRUE;
          $link['#attributes']['class'][] = 'draggable-disabled';
        }
      }
    }
  }

  if ($form_object instanceof MenuLinkEditForm) {
    $menuLinkId = $form['menu_link_id']['#value'] ?? '';
    if (str_contains($menuLinkId, 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.')) {
      $form['menu_parent']['#access'] = FALSE;
      $form['weight']['#access'] = FALSE;
    }
  }

  // @phpstan-ignore-next-line
  if ($form_object instanceof TaxonomyManagerForm) {
    $form['toolbar']['search_terms']['#prefix'] = '<div class="taxonomy-manager-autocomplete-input hidden mt-4">';
    $form['taxonomy']['#prefix'] = '<div class="flex-0">';
    $form['taxonomy']['#suffix'] = '</div>';
    $form['term-data']['#prefix'] = '<div class="flex-1"><div id="taxonomy-term-data-form">';
    $form['term-data']['#suffix'] = '</div></div>';
    $form['taxonomy'] = [
      '#prefix' => '<div class="flex gap-4">',
      '#suffix' => '</div>',
      'taxonomy' => $form['taxonomy'],
      'term-data' => $form['term-data'],
    ];
    unset($form['term-data']);
    $form['load-term-data']['#attributes']['class'][] = 'hidden';
  }

  // @phpstan-ignore-next-line
  if ($form_object instanceof TaxonomyManagerTermForm) {
    $form['#neo_style'] = 'flush';
    // @phpstan-ignore-next-line
    $term = $form_object->getEntity();
    /** @var \Drupal\taxonomy\VocabularyInterface $vocabulary */
    $vocabulary = \Drupal::entityTypeManager()->getStorage('taxonomy_vocabulary')->load($term->bundle());
    $controls = $vocabulary->getThirdPartySettings('neo_taxonomy');

    $form['fieldset']['original']['revision_information']['#access'] = FALSE;
    $form['fieldset']['original']['revision']['#access'] = FALSE;

    if (isset($controls['nest']) && empty($controls['nest'])) {
      $form['fieldset']['original']['relations']['#access'] = FALSE;
    }
  }
}

/**
 * After build callback to remove help and guidelines from description field.
 */
function neo_taxonomy_description_after_build($form_element, FormStateInterface $form_state) {
  if (isset($form_element['format'])) {
    unset($form_element['format']['help']);
    unset($form_element['format']['guidelines']);
  }
  return $form_element;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function neo_taxonomy_form_taxonomy_overview_vocabularies_alter(&$form, FormStateInterface $form_state) {
  $form['vocabularies']['#neo_style'] = [
    'label' => 'heading',
  ];
  foreach (Element::children($form['vocabularies']) as $key) {
    $form['vocabularies'][$key]['label'] = [
      '#markup' => neo_icon($form['vocabularies'][$key]['label']['#plain_text'], NULL, NULL, ['entity.taxonomy_vocabulary']),
    ];
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function neo_taxonomy_form_taxonomy_overview_terms_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\taxonomy\VocabularyInterface $vocabulary */
  $vocabulary = $form_state->get(['taxonomy', 'vocabulary']);
  $controls = $vocabulary->getThirdPartySettings('neo_taxonomy');

  $form['help']['#attributes']['class'][] = 'card bg-base-100 text-xs text-base-700 p-2';
  if (
    isset($controls['order']) && empty($controls['order'])
    ||
    isset($controls['nest']) && empty($controls['nest'])
  ) {
    if ($description = $vocabulary->getDescription()) {
      $form['help']['message']['#markup'] = $description;
    }
  }
  $hideWeight = FALSE;
  foreach (Element::children($form['terms']) as $key) {
    if ($form['terms'][$key]['weight'] === NULL) {
      $hideWeight = TRUE;
    }
  }
  if ($hideWeight || (isset($controls['order']) && empty($controls['order']))) {
    $form['actions']['reset_alphabetical']['#access'] = FALSE;
    unset($form['terms']['#tabledrag']);
    unset($form['terms']['#header']['weight']);
    foreach (Element::children($form['terms']) as $key) {
      unset($form['terms'][$key]['weight']);
    }
  }

  foreach (Element::children($form['terms']) as $key) {
    $form['terms'][$key]['status']['#markup'] = neo_icon_admin($form['terms'][$key]['status']['#markup'])->iconOnly();
    $term = $form['terms'][$key]['#term'] ?? NULL;

    $default = $form['terms'][$key]['term'];
    $form['terms'][$key]['term'] = [
      '#type' => 'html_tag',
      '#tag' => 'div',
      '#attributes' => [
        'class' => ['flex items-center gap-2'],
      ],
      'tid' => $default['tid'] ?? NULL,
      'parent' => $default['parent'] ?? NULL,
      'depth' => $default['depth'] ?? NULL,
      '#prefix' => $default['#prefix'] ?? '',
    ];
    unset($default['tid'], $default['parent'], $default['depth'], $default['#prefix']);
    $default['#field_prefix'] = 'asdf';
    $form['terms'][$key]['term']['title'] = $default;
    if ($term instanceof TermInterface) {
      $media = NULL;
      if ($term->hasField('field_image') && !$term->get('field_image')->isEmpty()) {
        $media = $term->get('field_image')->entity;
      }
      elseif ($term->hasField('field_media') && !$term->get('field_media')->isEmpty()) {
        $media = $term->get('field_media')->entity;
      }
      if ($media instanceof MediaInterface && $media->bundle() === 'image') {
        $neoImageStyle = new NeoImageStyle();
        $neoImageStyle->scaleCrop(30, 30);
        $form['terms'][$key]['term']['image'] = $neoImageStyle->toRenderableFromEntity($media, 'Alt Text', 'Title Text');
        $form['terms'][$key]['term']['image']['#attributes']['class'][] = 'rounded';
        $form['terms'][$key]['term']['image']['#weight'] = -10;
      }
      else {
        if ($term->hasField('field_icon') && !$term->get('field_icon')->isEmpty()) {
          $form['terms'][$key]['term']['icon'] = [
            '#type' => 'neo_icon',
            '#icon' => $term->get('field_icon')->value,
            '#weight' => -10,
          ];
        }
      }
    }
    if (isset($controls['link']) && empty($controls['link'])) {
      $form['terms'][$key]['term']['title']['#type'] = 'markup';
      $form['terms'][$key]['term']['title']['#markup'] = '<div>' . $form['terms'][$key]['term']['title']['#title'] . '</div>';
    }
  }
}

/**
 * Alter form for taxonomy vocabulary to add neo_taxonomy settings.
 */
function neo_taxonomy_form_alter_form_taxonomy_vocabulary(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\taxonomy\VocabularyInterface $vocabulary */
  $vocabulary = $form_object->getEntity();

  /** @var \Drupal\taxonomy\TermStorageInterface $taxonomy_storage */
  $taxonomy_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $hierarchy_type = $taxonomy_storage->getVocabularyHierarchyType($vocabulary->id());

  $controls = $vocabulary->getThirdPartySettings('neo_taxonomy');
  $elements = [
    '#type' => 'fieldset',
    '#title' => t('Settings'),
    '#tree' => TRUE,
  ];
  $elements['link'] = [
    '#type' => 'checkbox',
    '#title' => t('Link to Term'),
    '#description' => t('Allow terms to be linked on the management page.'),
    '#default_value' => !empty($controls['link']) || !isset($controls['link']),
  ];
  $elements['order'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable Ordering'),
    '#description' => t('Allow terms to be ordered.'),
    '#default_value' => !empty($controls['order']) || !isset($controls['order']),
  ];
  $elements['nest'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable Nesting'),
    '#description' => t('Allow terms to be nested.'),
    '#disabled' => $hierarchy_type !== 0,
    '#default_value' => !empty($controls['nest']) || !isset($controls['nest']) || $hierarchy_type !== 0,
    '#states' => [
      'visible' => [
        ':input[name="neo_taxonomy[order]"]' => ['checked' => TRUE],
      ],
    ],
  ];

  $options = array_map(function ($format) {
    return $format->label();
  }, filter_formats());
  $elements['description_format'] = [
    '#type' => 'select',
    '#title' => t('Description text format'),
    '#options' => $options,
    '#empty_option' => t('- Default -'),
    '#default_value' => $controls['description_format'] ?? '',
  ];

  // Insert after description.
  $keys = array_keys($form);
	$index = array_search('description', $keys);
	$pos = false === $index ? count($form) : $index + 1;
	$form = array_merge( array_slice($form, 0, $pos), ['neo_taxonomy' => $elements], array_slice($form, $pos) );

  $form['actions']['submit']['#submit'][] = 'neo_taxonomy_form_taxonomy_vocabulary_form_submit';
}

/**
 * Submit handler for commerce product form.
 */
function neo_taxonomy_form_taxonomy_vocabulary_form_submit(array $form, FormStateInterface $form_state) {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\taxonomy\VocabularyInterface $vocabulary */
  $vocabulary = $form_object->getEntity();

  $controls = $form_state->getValue('neo_taxonomy');
  $vocabulary->setThirdPartySetting('neo_taxonomy', 'link', !empty($controls['link']));
  $vocabulary->setThirdPartySetting('neo_taxonomy', 'order', !empty($controls['order']));
  $vocabulary->setThirdPartySetting('neo_taxonomy', 'nest', !empty($controls['order']) && !empty($controls['nest']));
  $vocabulary->setThirdPartySetting('neo_taxonomy', 'description_format', $controls['description_format'] ?? '');
  $vocabulary->save();
}

/**
 * Implements hook_library_info_alter().
 */
function neo_taxonomy_library_info_alter(&$libraries, $extension) {
  if ($extension == 'taxonomy_manager') {
    $libraries['form']['css'] = [];
  }
}
