taxonomy.vocabulary.*.third_party.neo_taxonomy:
  type: mapping
  label: Neo taxonomy
  mapping:
    link:
      type: boolean
      label: Link taxonomy
    order:
      type: boolean
      label: Order taxonomy
    nest:
      type: boolean
      label: Nest taxonomy
    description_format:
      type: string
      label: Description format
