views.style.table.neo:
  type: views.style.table
  label: 'Table with Neo options'
  mapping:
    info:
      type: sequence
      label: 'Columns info'
      sequence:
        type: mapping
        label:  'Column info'
        mapping:
          neo_style:
            type: string
            label: Neo Style
          neo_size:
            type: string
            label: Neo Size
          neo_align:
            type: string
            label: Neo Align

field.widget.settings.neo_options_buttons:
  type: mapping
  label: 'Neo Check boxes/radio buttons'
  mapping:
    style:
      type: string
      label: Style

field.widget.settings.neo_link:
  type: mapping
  label: 'Neo Link Widget'
  mapping:
    placeholder_url:
      type: string
      label: Placeholder for URL
    placeholder_title:
      type: string
      label: Placeholder for link title
    link_text_label:
      type: string
      label: Link text label
    linkit_profile:
      type: string
      label: Linkit Profile
    wrapper_type:
      type: string
      label: Wrapper Type
    icon:
      type: boolean
      label: Allow icon selection
    icon_required:
      type: boolean
      label: Require icon
    icon_libraries:
      type: sequence
      label: Icon Libraries
      sequence:
        type: string
    target:
      type: boolean
      label: Allow target selection
    class:
      type: boolean
      label: Allow class selection
    class_list:
      type: string
      label: List of allowed CSS classes


field.formatter.settings.neo_link:
  type: mapping
  label: 'Neo Link Formatter'
  mapping:
    trim_length:
      type: integer
      label: Trim Length
    rel:
      type: string
      label: Rel
    target:
      type: string
      label: Target
    title:
      type: string
      label: Title
    icon:
      type: string
      label: Icon
    position:
      type: string
      label: Position
    url_only:
      type: boolean
      label: URL Only
    url_plain:
      type: boolean
      label: URL Plain
    title_only:
      type: boolean
      label: Title Only


field.formatter.settings.neo_string:
  type: mapping
  label: 'Neo String Formatter'
  mapping:
    link_to_entity:
      type: boolean
      label: Link to entity
    style:
      type: string
      label: Style
    delimiter:
      type: string
      label: Delimiter
    prefix:
      type: string
      label: Prefix
    suffix:
      type: string
      label: Suffix
