<?php

/**
 * @file
 * Primary module hooks for Neo | Taxonomy module.
 */

declare(strict_types=1);

/**
 * Implements hook_page_attachments_alter().
 */
function neo_metatag_page_attachments_alter(array &$attachments) {
  foreach ($attachments['#attached']['html_head'] as $key => $value) {
    if ($value[1] == 'system_meta_generator') {
      unset($attachments['#attached']['html_head'][$key]);
    }
  }
}
