<?php

/**
 * @file
 * Primary module hooks for Neo | Taxonomy module.
 */

declare(strict_types=1);

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Menu\MenuLinkTreeElement;
use Drupal\Core\Render\Element;
use Drupal\neo_icon\IconElement;
use Drupal\menu_link_content\Entity\MenuLinkContent;
use Drupal\menu_link_content\Plugin\Menu\MenuLinkContent as MenuMenuLinkContent;
use Drupal\neo_menu_link\NeoMenuLinkDefault;
use Drupal\neo_menu_link\NeoMenuLinkLoginLogoutMenuLink;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function neo_menu_link_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'menu_link_content') {
    /** @var \Drupal\neo_menu_link\Settings\MenuLinkSettings $settings */
    $settings = \Drupal::service('neo_menu_link.settings')->getActive();
    $fields['link']->setDisplayOptions('form', [
      'type' => 'neo_link',
      'weight' => -2,
      'settings' => [
        'icon_libraries' => $settings->getValue('icon_libraries') ?? [],
        'target' => !empty($settings->getValue('target')),
        'class' => !empty($settings->getValue('class')),
        'class_list' => $settings->getClassList() ?? [],
      ],
    ]);
  }
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function neo_menu_link_menu_links_discovered_alter(&$links) {
  $links['user.logout']['class'] = 'Drupal\neo_menu_link\NeoMenuLinkLoginLogoutMenuLink';
}

/**
 * Implements hook_module_implements_alter().
 */
function neo_menu_link_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_node_form_alter') {
    $group = $implementations['neo_menu_link'];
    unset($implementations['neo_menu_link']);
    $implementations['neo_menu_link'] = $group;
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function neo_menu_link_form_node_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['menu'])) {
    /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
    $form_object = $form_state->getFormObject();
    $node = $form_object->getEntity();
    $defaults = menu_ui_get_menu_link_defaults($node);
    $options = [];
    if ($defaults['entity_id']) {
      $menu = MenuLinkContent::load($defaults['entity_id']);
      /** @var \Drupal\Core\Field $item */
      $item = $menu->get('link')->first();
      $options = $item->get('options')->getValue();
    }
    /** @var \Drupal\neo_menu_link\Settings\MenuLinkSettings $settings */
    $settings = \Drupal::service('neo_menu_link.settings')->getActive();
    $form['menu']['link']['title']['#weight'] = -2;
    $form['menu']['link']['options']['#tree'] = TRUE;
    $form['menu']['link']['options']['#weight'] = -1;
    $form['menu']['link']['options']['attributes']['#tree'] = TRUE;
    $libraries = $settings->getValue('icon_libraries');
    $form['menu']['link']['options']['attributes']['data-icon'] = [
      '#type' => 'neo_icon_select',
      '#title' => t('Icon'),
      '#default_value' => $options['attributes']['data-icon'] ?? NULL,
      '#libraries' => $libraries,
      '#access' => \Drupal::currentUser()->hasPermission('use neo_menu_link'),
    ];
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        if (($key = array_search('menu_ui_form_node_form_submit', $form['actions'][$action]['#submit'])) !== FALSE) {
          $form['actions'][$action]['#submit'][$key] = 'neo_menu_link_menu_ui_form_node_form_submit';
        }
      }
    }
  }
}

/**
 * Form submission handler for menu item field on the node form.
 *
 * @param array $form
 *   An associative array containing the structure of the form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 *
 * @see menu_ui_form_node_form_submit()
 */
function neo_menu_link_menu_ui_form_node_form_submit(array $form, FormStateInterface $form_state) {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_object->getEntity();
  if (!$form_state->isValueEmpty('menu')) {
    $values = $form_state->getValue('menu');
    if (empty($values['enabled'])) {
      if ($values['entity_id']) {
        $entity = MenuLinkContent::load($values['entity_id']);
        $entity->delete();
      }
    }
    elseif (trim($values['title'])) {
      // Decompose the selected menu parent option into 'menu_name' and
      // 'parent', if the form used the default parent selection widget.
      if (!empty($values['menu_parent'])) {
        list($menu_name, $parent) = explode(':', $values['menu_parent'], 2);
        $values['menu_name'] = $menu_name;
        $values['parent'] = $parent;
      }
      neo_menu_link_menu_ui_node_save($node, $values);
    }
  }
}

/**
 * Helper function to create or update a menu link for a node.
 *
 * @param \Drupal\node\NodeInterface $node
 *   Node entity.
 * @param array $values
 *   Values for the menu link.
 *
 * @see _menu_ui_node_save()
 */
function neo_menu_link_menu_ui_node_save(NodeInterface $node, array $values) {
  /** @var \Drupal\menu_link_content\MenuLinkContentInterface $entity */
  if (!empty($values['entity_id'])) {
    $entity = MenuLinkContent::load($values['entity_id']);
    if ($entity->isTranslatable()) {
      if (!$entity->hasTranslation($node->language()->getId())) {
        $entity = $entity->addTranslation($node->language()->getId(), $entity->toArray());
      }
      else {
        $entity = $entity->getTranslation($node->language()->getId());
      }
    }
  }
  else {
    // Create a new menu_link_content entity.
    $entity = MenuLinkContent::create([
      'link' => ['uri' => 'entity:node/' . $node->id()],
      'langcode' => $node->language()->getId(),
    ]);
    $entity->enabled->value = 1;
  }

  $entity->title->value = trim($values['title']);
  $entity->description->value = trim($values['description']);

  // Save link attributes as necessary.
  $link = $entity->link->first()->getValue();
  $link['options'] += ['attributes' => []];
  $link['options']['attributes'] = array_filter($values['options']['attributes'] + $link['options']['attributes']);
  $link['options'] = array_filter($link['options']);
  $entity->link->first()->setValue($link);

  $entity->menu_name->value = $values['menu_name'];
  $entity->parent->value = $values['parent'];
  $entity->weight->value = isset($values['weight']) ? $values['weight'] : 0;
  $entity->save();
}

/**
 * Implements hook_preprocess_menu().
 */
function neo_menu_link_preprocess_menu(&$variables) {
  $variables['items'] = neo_menu_link_preprocess_menu_items($variables['items']);
}

/**
 * Helper function to iterate over each menu item and utilize icon.
 */
function neo_menu_link_preprocess_menu_items($items) {
  foreach ($items as &$item) {
    $options = $item['url']->getOptions();
    if (!empty($options['attributes']['data-icon']) && !empty($item['title'])) {
      $position = isset($options['attributes']['data-icon-position']) ? $options['attributes']['data-icon-position'] : 'before';
      $icon = new IconElement($item['title'], $options['attributes']['data-icon']);
      $icon->iconPosition($position);
      $item['title'] = $icon->render();
      $item['url']->setOptions($options);
    }
    unset($options['attributes']['data-icon']);
    if (!empty($options['attributes']['data-class'])) {
      $options['attributes'] += ['class' => []];
      $classes = explode(' ', $options['attributes']['data-class']);
      $options['attributes']['class'] = array_merge($options['attributes']['class'], $classes);
      foreach ($classes as $class) {
        $item['attributes']->addClass($class . '-wrapper');
      }
    }
    unset($options['attributes']['data-class']);
    if (!empty($options['attributes']['data-target'])) {
      $options['attributes']['target'] = $options['attributes']['data-target'];
    }
    unset($options['attributes']['data-target']);
    if (!empty($item['below'])) {
      $item['below'] = neo_menu_link_preprocess_menu_items($item['below']);
    }
    $item['url']->setOptions($options);
  }
  return $items;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function neo_menu_link_form_menu_link_content_menu_link_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\neo_menu_link\Settings\MenuLinkSettings $settings */
  $settings = \Drupal::service('neo_menu_link.settings')->getActive();
  /** @var \Drupal\menu_link_content\Form\MenuLinkContentForm $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\menu_link_content\MenuLinkContentInterface $entity */
  $entity = $form_object->getEntity();
  $account = \Drupal::currentUser();
  if ($settings->getValue('spacers')) {
    // Set fields as non-required. We will check them in validation. We do this
    // because when spacer is enabled we set these dynamically but FormValidator
    // already checked #required and returns an error at this stage.
    $form['title']['widget'][0]['value']['#required'] = FALSE;
    $form['link']['widget'][0]['uri']['#required'] = FALSE;
    $spacer_enabled = FALSE;
    if (!$entity->isNew()) {
      $options = $entity->getUrlObject()->getOptions();
      $spacer_enabled = !empty($options['spacer']);
    }
    $html_id = Html::getUniqueId('neo-menu-link-spacer');
    $form['spacer'] = [
      '#type' => 'checkbox',
      '#title' => t('Show as spacer'),
      '#description' => t('If selected and this menu link will be used as a spacer between other links.'),
      '#default_value' => $spacer_enabled,
      '#id' => $html_id,
      '#weight' => -10,
    ];
    $form['spacer']['widget']['value']['#id'] = $html_id;
    foreach ([
      'title',
      'link',
      'expanded',
      'description',
    ] as $key) {
      $form[$key]['#states'] = [
        'invisible' => [
          '#' . $html_id => ['checked' => TRUE],
        ],
      ];
    }
    array_unshift($form['#validate'], 'neo_menu_link_form_menu_link_content_menu_link_content_form_validate');
  }
}

/**
 * Validation callback for menu link form.
 */
function neo_menu_link_form_menu_link_content_menu_link_content_form_validate(&$form, FormStateInterface $form_state) {
  if ($form_state->getValue(['spacer'], FALSE)) {
    $form_state->setValue(['title', 0, 'value'], 'Spacer');
    $form_state->setValue(['link', 0, 'uri'], '#');
    $form_state->setValue(['link', 0, 'options', 'spacer'], TRUE);
  }
  else {
    if (!$form_state->getValue(['title', 0, 'value'], FALSE)) {
      $form_state->setError($form['title']['widget'][0]['value'], t('@name field is required.', ['@name' => $form['title']['widget'][0]['value']['#title']]));
    }
    if (!$form_state->getValue(['link', 0, 'uri'], FALSE)) {
      $form_state->setError($form['link']['widget'][0]['uri'], t('@name field is required.', ['@name' => $form['link']['widget'][0]['uri']['#title']]));
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function neo_menu_link_form_menu_link_edit_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\neo_menu_link\Settings\MenuLinkSettings $settings */
  $settings = \Drupal::service('neo_menu_link.settings')->getActive();
  $access = \Drupal::currentUser()->hasPermission('use neo_menu_link');

  $options = $form_state->getBuildInfo()['args'][0]->getOptions();
  $form['path']['link']['data-icon'] = [
    '#type' => 'neo_icon_select',
    '#title' => t('Icon'),
    '#default_value' => $options['attributes']['data-icon'] ?? NULL,
    '#packages' => $settings->getValue('icon_libraries'),
    '#access' => $access,
  ];
  if (!empty($settings->getValue('target'))) {
    $form['path']['link']['data-target'] = [
      '#type' => 'checkbox',
      '#title' => t('Open link in new window'),
      '#description' => t('If selected, the menu link will open in a new window/tab when clicked.'),
      '#default_value' => $options['attributes']['data-target'] ?? NULL,
      '#return_value' => '_blank',
      '#access' => $access,
    ];
  }
  if (!empty($settings->getValue('class'))) {
    if ($listOptions = $settings->getClassList()) {
      $form['path']['link']['data-class'] = [
        '#type' => 'select',
        '#title' => t('CSS classes'),
        '#options' => $listOptions,
        '#empty_option' => t('- None -'),
        '#description' => t('Enter space-separated CSS class names that will be added to the link.'),
        '#default_value' => $options['attributes']['data-class'] ?? NULL,
        '#access' => $access,
      ];
    }
    else {
      $form['path']['link']['data-class'] = [
        '#type' => 'textfield',
        '#title' => t('CSS classes'),
        '#description' => t('Enter space-separated CSS class names that will be added to the link.'),
        '#default_value' => $options['attributes']['data-class'] ?? NULL,
        '#access' => $access,
      ];
    }
  }

  $form['path']['link']['title'] = [
    '#type' => 'textfield',
    '#title' => t('Description'),
    '#default_value' => $options['attributes']['title'] ?? NULL,
    '#access' => $access,
  ];

  $form['#submit'][] = 'neo_menu_link_form_menu_link_edit_alter_submit';
}

/**
 * Process the submitted form.
 *
 * @param array $form
 *   An associative array containing the structure of the form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 */
function neo_menu_link_form_menu_link_edit_alter_submit(array $form, FormStateInterface $form_state) {
  $menu_link_id = $form_state->getValue('menu_link_id');
  if (!empty($menu_link_id)) {
    $menu_link_manager = \Drupal::service('plugin.manager.menu.link');
    $options = $form_state->getBuildInfo()['args'][0]->getOptions();
    foreach (['title'] as $key) {
      $options['attributes'][$key] = $form_state->getValue($key);
    }
    foreach (['icon', 'target', 'class'] as $key) {
      $options['attributes']['data-' . $key] = $form_state->getValue('data-' . $key);
    }
    $menu_link_manager->updateDefinition($menu_link_id, ['options' => $options]);
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function neo_menu_link_form_menu_edit_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (empty($form['links']['links'])) {
    return;
  }
  foreach (Element::children($form['links']['links']) as $key) {
    $element = &$form['links']['links'][$key];
    $element['title']['#neo_style'] = 'heading';
    $element['operations']['#neo_size'] = 'min';
    $item = $element['#item'];
    $icon = NULL;
    if ($item instanceof MenuLinkTreeElement) {
      $link = $item->link;
      if ($link instanceof NeoMenuLinkDefault) {
        $icon = $link->getOptions()['attributes']['data-icon'] ?? NULL;
      }
      elseif ($link instanceof MenuMenuLinkContent || $link instanceof NeoMenuLinkLoginLogoutMenuLink) {
        $definition = $link->getPluginDefinition();
        $icon = $definition['options']['attributes']['data-icon'] ?? NULL;
      }
    }
    if ($icon) {
      if (is_array($element['title'])) {
        if (isset($element['title'][1]['#title'])) {
          $element['title'][1]['#title'] = neo_icon($element['title'][1]['#title'], $icon);
        }
      }
      else {
        $element['title'] = neo_icon($element['title'], $icon);
      }
    }
  }
}

/**
 * Implements hook_config_schema_info_alter().
 */
function neo_menu_link_config_schema_info_alter(&$definitions) {
  if (isset($definitions['core.menu.static_menu_link_overrides'])) {
    $schema = [
      'options' => [
        'type' => 'mapping',
        'label' => 'Options',
        'mapping' => [
          'attributes' => [
            'type' => 'mapping',
            'title' => 'Attributes',
            'mapping' => [
              'data-icon' => [
                'type' => 'string',
                'label' => 'Icon',
              ],
              'data-target' => [
                'type' => 'boolean',
                'label' => 'Target',
              ],
              'data-class' => [
                'type' => 'string',
                'label' => 'Class',
              ],
              'title' => [
                'type' => 'string',
                'label' => 'Title',
              ],
            ],
          ],
        ],
      ],
    ];
    $definitions['core.menu.static_menu_link_overrides']['mapping']['definitions']['sequence']['mapping'] += $schema;
  }
}
